### ISSUE TITLE
Add support for babel-plugin-macros

### ISSUE THREAD

**Issue by tlenex** [michellocana/babel-plugin-jsx-auto-test-id#7]
Very nice plugin @michellocana ! But it can't be used in create-react-app without ejecting :(

However, `babel-plugin-macros` exists! and it is supported by cra.
https://www.npmjs.com/package/babel-plugin-macros

Can we generate macro file for this package?  
https://github.com/kentcdodds/babel-plugin-macros/blob/master/other/docs/author.md

If done, it would be nice to add this package to https://github.com/jgierer12/awesome-babel-macros to boost package usage and interest.

**Comment by michellocana** [comment]
Hey @tlenex, glad you liked this plugin :). I think you can customize the CRA configuration through this package without ejecting https://github.com/arackaf/customize-cra

**Comment by tlenex** [comment]
I know, but is causes problems when upgrading `react-scripts` and introduces new dependencies to the project. `babel-plugin-macros` does not.
